### ISSUE TITLE
[code analysis] handle nullable types

### ISSUE THREAD

**Issue by khemichew** [mutatecsharp/mutate-csharp#1]
The mutation operators should handle nullable types in CSharp - an example is provided below:

```csharp
int? x = 0;
int? y = null;
```

compiles to:

```csharp
Nullable<int> x = 0;
Nullable<int> y = null;
```

A solution would be to get the underlying type that instantiates the Nullable generic type.

**Comment by mutatecsharp** [comment]
resolved.
